# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ru-RU"
title                    : "Михаил Коротеев"
title_separator          : "|"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Михаил Коротеев"
description              : ""
url                      : "https://koroteev.site"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : koroteevmv/koroteevmv.github.io
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/android-chrome-192x192.png # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "facebook"
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : 5
    colorscheme          : "light"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : false # true, false (default)
search_full_content      : false # true, false (default)
search_provider          : algolia

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification : 77706580
naver_site_verification  :

# Social Sharing
twitter:
  username               : koroteev_m
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/android-chrome-192x192.png
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-1K09X3NDBE
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Михаил Коротеев"
  avatar           : "/assets/images/avatar3.jpg"
  bio              : "Есть такая профессия - Родину автоматизировать."
  # location         : "Москва"
  # email            : koroteevmv@gmail.com
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://koroteev.site"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      # url: "https://www.linkedin.com/in/koroteevmv/"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/koroteevmv"

    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCPe6h6MY8XZpLV7oRLqRUwQ"

    - label: "Elibrary"
      icon: "fab fa-fw fa-erlang"
      url: "https://elibrary.ru/author_items.asp?authorid=647967"

    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8768-6564"

    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/mihail.koroteev"

    - label: "Vkontakte"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/koroteev_m"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: https://twitter.com/koroteev_m

      # https://fontawesome.com/icons?d=gallery

# Site Footer
footer:
  links:
    # - label: "Facebook"
      # icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/mihail.koroteev"

    - label: "Vkontakte"
      icon: "fab fa-fw fa-vk"
      url: "https://vk.com/koroteev_m"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/koroteev_m


# Reading Files
include:
  - .htaccess
  - _pages
  - _courses
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  scipop:
    output: true
    permalink: /:collection/:path/
  os:
    output: true
    permalink: /:collection/:path/
  text:
    output: true
    permalink: /:collection/:path/
  ml:
    output: true
    permalink: /:collection/:path/
  md:
    output: true
    permalink: /:collection/:path/
  pd:
    output: true
    permalink: /:collection/:path/
  wd:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: None
      author_profile: true
      read_time: true
      share: false
      comments: false
      related: true
      toc: true
      toc_sticky: true
      show_date: true
  # text
  - scope:
      path: "_text"
      type: text
    values:
      layout: textbook_page
      read_time: true
      show_date: false
      author_profile: false
      share: false
      comments: false
      related: true
      last_modified_at: false
      toc: false
      word_count: true
      
  # os
  - scope:
      path: "_os"
      type: os
    values:
      layout: coursepage
      read_time: false
      show_date: false
      author_profile: false
      share: false
      comments: false
      related: false
      last_modified_at: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "os"
  # md
  - scope:
      path: "_md"
      type: md
    values:
      layout: coursepage
      read_time: false
      show_date: false
      author_profile: false
      share: false
      comments: false
      related: false
      last_modified_at: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "md"
  # ml
  - scope:
      path: "_ml"
      type: ml
    values:
      layout: coursepage
      read_time: false
      show_date: false
      author_profile: false
      share: false
      comments: false
      related: false
      last_modified_at: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "ml"
  # wd
  - scope:
      path: "_wd"
      type: wd
    values:
      layout: coursepage
      read_time: false
      show_date: false
      author_profile: false
      share: false
      comments: false
      related: false
      last_modified_at: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "wd"
        
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
